import numpy as np
from OrbitPropagator import OrbitPropagator, null_perturbations
import Constants as ct


if __name__ == '__main__':
    height_sat = 500 # (in km) Height of the Satellite
    pc_threshold = 0.0001
    # State of Satellite at TCA
    # Note - All the values except Semi-major axis and Eccentricity, was generated by random number generator.
    r_sat_tca, v_sat_tca = OrbitPropagator.Kep2State((ct.Earth['radius']+height_sat), 1e-6, 26.95, 90.41, 286.05, 287.82, cb=ct.Earth)

    # State of Debri at TCA
    r_deb_tca = r_sat_tca + np.array([1e-6, 1e-6, 1e-6])
    v_deb_tca = np.array([4.7262, -5.3674, 3.3146])

    print(r_deb_tca)
    print(v_sat_tca)
    print(OrbitPropagator.State2Kep(np.array([r_deb_tca]),np.array([v_deb_tca]), cb=ct.Earth))


    # collision_Prob = OrbitPropagator.Pc2D(r0_S, v0_S, ct.CubeSat['Covarience_Matrix'], r0_D, v0_D, ct.Debri['Covarience_Matrix'], (ct.CubeSat['HBR_Radius']+ct.Debri['HBR_Radius']))
    # print(collision_Prob)

    # Time span and time step
    tspan = (0.02) * (60*60) # hours
    dt = 10 # seconds

    # Propagate orbit
    perturbations = null_perturbations()
    perturbations['J2'] = True
    perturbations['J3'] = True
    perturbations['Drag'] = True
    perturbations['SRP'] = True
    perturbations['External Thrust'] = False
    
    # ob_S = OrbitPropagator(r0_S,v0_S,tspan,dt,cb=ct.Earth,ob=ct.CubeSat,perturbations=perturbations)
    # ob_D = OrbitPropagator(r0_D,v0_D,tspan,dt,cb=ct.Earth,ob=ct.Debri,perturbations=perturbations)


    # OrbitPropagator.PlotOrbits([ob_S.rs], labels=['Satellite'], cb=ct.Earth, title='Test')
    # OrbitPropagator.PlotOrbits([ob_S.rs, ob_D.rs], labels=['Satellite', 'Debri'], cb=ct.Earth, title='Synthetic Collision Situation')
    # OrbitPropagator.PlotKepOrbits(ob_S.rs,ob_S.vs,ob_S.ts,cb=ct.Earth,title="Evolution of Satellite's Keplerian Elements")
    # OrbitPropagator.PlotEnergy(ob_S.rs,ob_S.vs,ob_S.ts,cb=ct.Earth,title="Specific Energy vs. Time")